/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The per-element breakdown of a weapon's Attack Rating. */
export interface ArBreakdown {
  total: number
  physical: number
  blunt: number
  thrust: number
  arcane: number
  fire: number
  bolt: number
  blood: number
  convertedElement: ConvertedElement
}

/** The body slot a piece of attire occupies (mirrors `bb_calc::ArmorKind`). */
export declare const enum ArmorKind {
  Head = 'Head',
  Chest = 'Chest',
  Hands = 'Hands',
  Legs = 'Legs',
  Other = 'Other'
}

/**
 * A gem the player owns, ready to feed the optimizer. `shape` is the
 * inventory-sourced shape (authoritative for slotting) and is kept separate
 * from the gem's calc fields, which never include shape.
 */
export interface Candidate {
  gem: Gem
  shape: GemShape
  gemRef: GemRef
}

/** A hunter's character data: name plus every scalar field read from the save. */
export interface Character {
  name: string
  /** Soul level as stored in the save (the in-game level, not the stat sum). */
  level: number
  vitality: number
  endurance: number
  strength: number
  skill: number
  bloodtinge: number
  arcane: number
  health: number
  stamina: number
  insight: number
  bloodEchoes: number
  /** New-game cycle: 0 = NG, 1 = NG+1, 2 = NG+2, … */
  newGame: number
  /** Total playtime in milliseconds. */
  playtimeMs: number
}

/**
 * Computes the Attack Rating for the weapon with `weapon_id`, fitted with up
 * to three `gems` at the given hunter `stats`. Gem slot order does not matter.
 */
export declare function computeAr(weaponId: string, gems: Array<Gem>, stats: Stats): ArBreakdown

/** The element a "Conv" weapon's physical damage is converted to. */
export declare const enum ConvertedElement {
  Phys = 'Phys',
  Bolt = 'Bolt',
  Fire = 'Fire',
  Arc = 'Arc'
}

/**
 * Which figure {@link optimizeForSlots} maximizes. `Total` is the full Attack
 * Rating; the rest target a single damage line (mirrors `bb_calc::DamageTarget`).
 */
export declare const enum DamageTarget {
  Total = 'Total',
  Phys = 'Phys',
  Blunt = 'Blunt',
  Thrust = 'Thrust',
  Arcane = 'Arcane',
  Fire = 'Fire',
  Bolt = 'Bolt',
  Blood = 'Blood'
}

/**
 * A blood gem. Multiplier fields (`dmg*`) default to `1.0` for no effect;
 * scaling and flat (`*scale`, `flat*`) fields default to `0.0`.
 */
export interface Gem {
  name: string
  source: string
  tier: number
  shape: GemShape
  arcScale: number
  strScale: number
  sklScale: number
  bltScale: number
  dmgGeneral: number
  dmgArcane: number
  dmgFire: number
  dmgBolt: number
  dmgPhys: number
  dmgBlood: number
  dmgBlunt: number
  dmgThrust: number
  flatPhys: number
  flatArcane: number
  flatFire: number
  flatBolt: number
  flatBlood: number
  openFoes: number
  striking: number
  kinhunter: number
  beasthunter: number
}

/** A minimal identity for reporting which owned gem the optimizer chose. */
export interface GemRef {
  id: string
  name: string
  effects: Array<string>
}

/** The physical shape of a blood gem (mirrors `bb_calc::GemShape`). */
export declare const enum GemShape {
  Radial = 'Radial',
  Triangle = 'Triangle',
  Waning = 'Waning',
  Circle = 'Circle',
  /** Universal wildcard: a Droplet gem fits any slot. */
  Droplet = 'Droplet'
}

/** Returns every weapon in the game. */
export declare function getWeapons(): Array<Weapon>

export interface Inventory {
  character: Character
  stats: Stats
  gems: Array<InventoryGem>
  weapons: Array<OwnedWeapon>
  armor: Array<OwnedArmor>
  items: Array<OwnedItem>
}

export interface InventoryGem {
  id: string
  name: string
  shape: GemShape
  rating: number
  effects: Array<string>
  /** Whether this gem is currently socketed in a weapon. */
  inUse: boolean
}

/** The kind of a non-equipment item (mirrors `bb_calc::ItemCategory`). */
export declare const enum ItemCategory {
  Consumable = 'Consumable',
  Material = 'Material',
  Key = 'Key',
  Chalice = 'Chalice'
}

/** Where an owned item lives (mirrors `bb_calc::ItemLocation`). */
export declare const enum ItemLocation {
  Inventory = 'Inventory',
  Storage = 'Storage'
}

export declare const enum Mode {
  Compare = 'Compare',
  Plan = 'Plan'
}

/**
 * Finds the socketing of `candidates` that maximizes `target` for the weapon
 * with `weapon_id`, using that weapon variant's own baked-in imprint slots
 * (Normal/Uncanny/Lost are distinct ids). Prefer this over {@link optimizeForSlots}
 * unless the slots come from somewhere other than the chosen weapon.
 *
 * Returns a `Promise`: the search runs on a worker thread so it never blocks
 * the caller (required in the browser, where the optimizer's threaded
 * `Mode::Compare` would otherwise call `Atomics.wait` on the main thread).
 */
export declare function optimize(weaponIds: Array<string>, gems: Array<InventoryGem>, stats: Stats, target: DamageTarget, mode: Mode, excludedGems?: Array<string> | undefined | null): Promise<unknown>

/** The winning socketing found by {@link optimizeForSlots}. */
export interface OptimizeResult {
  /** The value of the optimized metric (see {@link DamageTarget}). */
  score: number
  /** The full Attack Rating of the winning socketing, regardless of target. */
  total: number
  breakdown: ArBreakdown
  slots: Array<SlotChoice>
  weaponId: string
}

/** A piece of attire the player owns, decoded from a save. */
export interface OwnedArmor {
  canonicalId: number
  name: string
  kind: ArmorKind
  location: ItemLocation
}

/** A non-equipment item the player owns, decoded from a save. */
export interface OwnedItem {
  canonicalId: number
  name: string
  category: ItemCategory
  amount: number
  location: ItemLocation
}

/** A weapon the player owns, decoded from a save. */
export interface OwnedWeapon {
  /** In-game id with the upgrade level stripped (base + imprint). */
  canonicalId: number
  name: string
  hand: WeaponHand
  imprint: WeaponImprint
  level: number
  location: ItemLocation
  /** The AR-table slug when this is a right-hand weapon we can optimize. */
  weaponId?: string
  /** Instance ids (hex) of gems socketed in this weapon, in slot order. */
  gemIds: Array<string>
}

export declare function parseSave(saveFile: Uint8Array): Promise<unknown>

/**
 * One imprint slot in the result: its shape and the owned gem placed in it
 * (`gem` is absent when the optimizer left the slot empty).
 */
export interface SlotChoice {
  slot: number
  slotShape: GemShape
  gem?: GemRef
}

/** The four hunter stats that drive weapon scaling. */
export interface Stats {
  str: number
  skl: number
  blt: number
  arc: number
}

/** A weapon and its base damage values, exposed to JavaScript. */
export interface Weapon {
  id: string
  /**
   * In-game numeric id for matching owned weapons from a save; absent for
   * calc-only variants (tricked forms, rune transforms).
   */
  canonicalId?: number
  name: string
  weaponType: WeaponType
  phys: number
  blood: number
  arcane: number
  fire: number
  bolt: number
  /** Imprint gem-slot shapes, baked in per weapon variant (Normal/Uncanny/Lost). */
  gemSlot1: GemShape
  gemSlot2: GemShape
  gemSlot3: GemShape
}

/** Which hand a weapon is wielded in (mirrors `bb_calc::WeaponHand`). */
export declare const enum WeaponHand {
  Right = 'Right',
  Left = 'Left'
}

/** A weapon's imprint (mirrors `bb_calc::WeaponImprint`). */
export declare const enum WeaponImprint {
  Normal = 'Normal',
  Uncanny = 'Uncanny',
  Lost = 'Lost'
}

/** How a weapon's damage is derived (mirrors `bb_calc::WeaponType`). */
export declare const enum WeaponType {
  Dual = 'Dual',
  Conv = 'Conv',
  Blood = 'Blood'
}
