/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The per-element breakdown of a weapon's Attack Rating. */
export interface ArBreakdown {
  total: number
  physical: number
  blunt: number
  thrust: number
  arcane: number
  fire: number
  bolt: number
  blood: number
  convertedElement: ConvertedElement
}

/**
 * Computes the Attack Rating for the weapon with `weapon_id`, fitted with up
 * to three `gems` at the given hunter `stats`. Gem slot order does not matter.
 */
export declare function computeAr(weaponId: string, gems: Array<Gem>, stats: Stats): ArBreakdown

/** The element a "Conv" weapon's physical damage is converted to. */
export declare const enum ConvertedElement {
  Phys = 'Phys',
  Bolt = 'Bolt',
  Fire = 'Fire',
  Arc = 'Arc',
}

/**
 * A blood gem. Multiplier fields (`dmg*`) default to `1.0` for no effect;
 * scaling and flat (`*scale`, `flat*`) fields default to `0.0`.
 */
export interface Gem {
  name: string
  source: string
  tier: number
  shape: GemShape
  arcScale: number
  strScale: number
  dmgGeneral: number
  dmgArcane: number
  dmgFire: number
  dmgBolt: number
  dmgPhys: number
  dmgBlood: number
  dmgBlunt: number
  dmgThrust: number
  flatPhys: number
  flatArcane: number
  flatFire: number
  flatBolt: number
  flatBlood: number
  openFoes: number
  striking: number
  kinhunter: number
  beasthunter: number
}

/** The physical shape of a blood gem (mirrors `bb_calc::GemShape`). */
export declare const enum GemShape {
  Radial = 'Radial',
  Triangle = 'Triangle',
  Waning = 'Waning',
  Circle = 'Circle',
}

/** Returns every weapon in the game. */
export declare function getWeapons(): Array<Weapon>

/** The four hunter stats that drive weapon scaling. */
export interface Stats {
  str: number
  skl: number
  blt: number
  arc: number
}

/** A weapon and its base damage values, exposed to JavaScript. */
export interface Weapon {
  id: string
  name: string
  weaponType: WeaponType
  phys: number
  blood: number
  arcane: number
  fire: number
  bolt: number
}

/** How a weapon's damage is derived (mirrors `bb_calc::WeaponType`). */
export declare const enum WeaponType {
  Dual = 'Dual',
  Conv = 'Conv',
  Blood = 'Blood',
}
